int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.

lib{json}: {hxx ixx txx}{** -version} $imp_libs $int_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{json}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $int_libs
}

# Install into the libjson/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libjson/
  install.subdirs = true
}
