int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
if ($cxx.target.class == 'linux')
{
  imp_libs =+ dl%libs{dl}
}

liba{glad}: {h c}{** -version} $imp_libs $int_libs

c.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: c.poptions += 

# Export options.
#
liba{glad}:
{
  c.export.poptions = "-I$out_root" "-I$src_root"
  c.export.libs = $int_libs
}

# Install into the glad/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{h}{*}:
{
  install         = include/glad/
  install.subdirs = true
}
